// Centralized Logo & Branding Helper for StreamBazaar Storefront

// ── CUSTOM ICON OVERRIDES ──────────────────────────────────────────────────
export const CUSTOM_ICONS = {
  'hoichoi': '/hoichoi.jpg',
  'discovery plus': '/discoveryplus.jpg',
  'discovery+': '/discoveryplus.jpg',
  'discovery': '/discoveryplus.jpg',
  'lionsgate': '/lionsgateplay.jpg',
  'lionsgate play': '/lionsgateplay.jpg',
  'lionsgateplay': '/lionsgateplay.jpg',
  'netflix': 'https://logo.clearbit.com/netflix.com',
  'spotify': 'https://logo.clearbit.com/spotify.com',
  'crunchyroll': 'https://logo.clearbit.com/crunchyroll.com',
  'apple': 'https://logo.clearbit.com/apple.com',
  'zee5': 'https://logo.clearbit.com/zee5.com',
  'jiohotstar': '/jiohotstar.png',
  'jio hotstar': '/jiohotstar.png',
  'hotstar': '/jiohotstar.png',
  'sonyliv': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/SonyLIV_2020.png',
  'sony liv': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/SonyLIV_2020.png',
  'amazon': 'https://logo.clearbit.com/primevideo.com',
  'prime video': 'https://logo.clearbit.com/primevideo.com',
  'chatgpt': 'https://logo.clearbit.com/openai.com',
  'openai': 'https://logo.clearbit.com/openai.com',
  'midjourney': 'https://logo.clearbit.com/midjourney.com',
  'claude': 'https://logo.clearbit.com/anthropic.com',
  'canva': 'https://logo.clearbit.com/canva.com'
};

// ── GAME COVER IMAGES ──────────────────────────────────────────────────────
export const GAME_IMGS = {
  'wwe 2k25': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2315690/capsule_184x69.jpg',
  'wwe bundles': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2315690/capsule_184x69.jpg',
  'forza horizon 5': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/capsule_184x69.jpg',
  'gta v': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/capsule_184x69.jpg',
  'gta trilogy': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1546930/capsule_184x69.jpg',
  'spider-man 2': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/capsule_184x69.jpg',
  'spider-man series': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1817070/capsule_184x69.jpg',
  'uncharted': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659420/capsule_184x69.jpg',
  'the last of us': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1888930/capsule_184x69.jpg',
  'black myth wukong': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/capsule_184x69.jpg',
  'ghost of tsushima': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215430/capsule_184x69.jpg',
  'elden ring': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_184x69.jpg',
  'resident evil': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/capsule_184x69.jpg',
  'hogwarts legacy': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/990080/capsule_184x69.jpg',
  'god of war': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1593500/capsule_184x69.jpg',
  'cyberpunk 2077': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/capsule_184x69.jpg',
  'pragmata': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1240440/capsule_184x69.jpg',
  'assassin\'s creed': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2208920/capsule_184x69.jpg',
  'f1 24': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2488620/capsule_184x69.jpg',
  'f1 25': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3059520/capsule_184x69.jpg',
  'stellar blade': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3489700/capsule_184x69.jpg',
  'mafia': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1030840/capsule_184x69.jpg',
  'tekken 7': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/389730/capsule_184x69.jpg',
  'tekken 8': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1778820/capsule_184x69.jpg',
  'expedition 33': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2690040/capsule_184x69.jpg',
  'red dead redemption': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/capsule_184x69.jpg',
  'hitman': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/capsule_184x69.jpg',
  'far cry': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2369390/capsule_184x69.jpg',
  'poppy playtime': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1721470/capsule_184x69.jpg',
  'minecraft': 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1240440/capsule_184x69.jpg'
};

// ── DOMAIN MAPPINGS (Extracted & Consolidated from Logo.dev Categories) ──
export const DOMAINS = {
  "10x genomics": "10xgenomics.com",
  "1password": "1password.com",
  "1stdibs": "1stdibs.com",
  "2k": "2k.com",
  "3m": "3m.com",
  "7 up": "7up.com",
  "7-eleven": "7-eleven.com",
  "aaa": "aaa.com",
  "abbott": "abbott.com",
  "abbvie": "abbvie.com",
  "abc news": "abcnews.com",
  "abercrombie &amp; fitch": "abercrombie.com",
  "abnormal security": "abnormalsecurity.com",
  "accenture": "accenture.com",
  "accor": "accor.com",
  "acer": "acer.com",
  "acorns": "acorns.com",
  "activision": "activision.com",
  "acura": "acura.com",
  "adept": "adept.ai",
  "adidas": "adidas.com",
  "adobe": "adobe.com",
  "adobe creative": "adobe.com",
  "adventhealth": "adventhealth.com",
  "advil": "advil.com",
  "adyen": "adyen.com",
  "aer lingus": "aerlingus.com",
  "aeroméxico": "aeromexico.com",
  "aetna": "aetna.com",
  "affirm": "affirm.com",
  "aflac": "aflac.com",
  "agoda": "agoda.com",
  "aha": "aha.video",
  "ai21 labs": "ai21.com",
  "air canada": "aircanada.com",
  "air china offers": "airchina.com",
  "air france": "airfrance.com",
  "air india": "airindia.com",
  "air new zealand": "airnewzealand.com",
  "airbnb": "airbnb.com",
  "airtable": "airtable.com",
  "airtel": "airtelxstream.in",
  "airtel xstream": "airtelxstream.in",
  "airwallex": "airwallex.com",
  "akamai": "akamai.com",
  "al jazeera": "aljazeera.com",
  "alamo rent a car": "alamo.com",
  "alaska airlines": "alaskaair.com",
  "aldo shoes": "aldoshoes.com",
  "alfa romeo": "alfaromeo.com",
  "alibaba.com": "alibaba.com",
  "aliexpress": "aliexpress.com",
  "all nippon airways": "ana.co.jp",
  "allbirds": "allbirds.com",
  "allegiant air": "allegiantair.com",
  "allianz": "allianz.com",
  "allstate": "allstate.com",
  "ally financial": "ally.com",
  "altbalaji": "altt.co.in",
  "aman": "aman.com",
  "amazon": "primevideo.com",
  "amazon e-commerce": "amazon.com",
  "amazon prime": "primevideo.com",
  "amc+": "amcplus.com",
  "amd": "amd.com",
  "american airlines": "aa.com",
  "american eagle": "ae.com",
  "american express": "americanexpress.com",
  "american family insurance": "amfam.com",
  "amgen": "amgen.com",
  "amplitude": "amplitude.com",
  "anthropic": "anthropic.com",
  "anthropologie": "anthropologie.com",
  "anz": "anz.com",
  "apollo global management": "apollo.com",
  "apple": "apple.com",
  "apple music": "music.apple.com",
  "apple tv": "tv.apple.com",
  "apple tv+": "tv.apple.com",
  "applebee&#x27;s": "applebees.com",
  "aquafina": "aquafina.com",
  "arbys": "arbys.com",
  "arctic wolf": "arcticwolf.com",
  "ares management": "ares.com",
  "aritzia": "aritzia.com",
  "arizona cardinals": "azcardinals.com",
  "arizona state university": "asu.edu",
  "arm holdings": "arm.com",
  "ars technica": "arstechnica.com",
  "asana": "asana.com",
  "asics": "asics.com",
  "asml": "asml.com",
  "asos": "asos.com",
  "associated press": "apnews.com",
  "aston martin": "astonmartin.com",
  "astrazeneca": "astrazeneca.com",
  "asus": "asus.com",
  "at&amp;t": "att.com",
  "atlanta falcons": "atlantafalcons.com",
  "atlassian": "atlassian.com",
  "auburn university": "auburn.edu",
  "audemars piguet": "audemarspiguet.com",
  "audi": "audi.com",
  "audible": "audible.com",
  "auth0": "auth0.com",
  "avant": "avant.com",
  "avast": "avast.com",
  "avg": "avg.com",
  "avianca": "avianca.com",
  "avis": "avis.com",
  "aviva plc": "aviva.com",
  "axa": "axa.com",
  "axios": "axios.com",
  "axis bank": "axisbank.com",
  "bacardi": "bacardi.com",
  "back market": "backmarket.com",
  "baidu": "baidu.com",
  "bain &amp; company": "bain.com",
  "balenciaga": "balenciaga.com",
  "balmain": "balmain.com",
  "baltimore ravens": "baltimoreravens.com",
  "banco bradesco": "bradesco.com.br",
  "bandai namco entertainment america inc": "bandainamcoent.com",
  "bank of america": "bankofamerica.com",
  "barclays": "barclays.com",
  "barracuda": "barracuda.com",
  "baxter international": "baxter.com",
  "bayer": "bayer.com",
  "baylor university": "baylor.edu",
  "bbc": "bbc.com",
  "bd": "bd.com",
  "bed bath &amp; beyond": "bedbathandbeyond.com",
  "bell canada": "bell.ca",
  "ben": "benjerry.com",
  "bentley": "bentleymotors.com",
  "bereal": "bereal.com",
  "berkshire hathaway": "berkshirehathaway.com",
  "berluti": "berluti.com",
  "best buy": "bestbuy.com",
  "best western hotels": "bestwestern.com",
  "bethesda softworks": "bethesda.net",
  "betterment": "betterment.com",
  "bill": "bill.com",
  "bills": "buffalobills.com",
  "binance": "binance.com",
  "biogen": "biogen.com",
  "biontech rd": "biontech.com",
  "birdies": "birdies.com",
  "birkenstock": "birkenstock.com",
  "bitdefender": "bitdefender.com",
  "bitwarden": "bitwarden.com",
  "blackrock": "blackrock.com",
  "blackstone": "blackstone.com",
  "blizzard entertainment": "blizzard.com",
  "block": "block.xyz",
  "bloomberg": "bloomberg.com",
  "blue apron": "blueapron.com",
  "bluesky": "bsky.app",
  "bmo": "bmo.com",
  "bmw": "bmw.com",
  "bmw usa": "bmw.com",
  "bnp paribas": "bnpparibas.com",
  "boeing": "boeing.com",
  "bojangles": "bojangles.com",
  "bol": "bol.com",
  "bolt": "bolt.com",
  "bombas": "bombas.com",
  "bonanza": "bonanza.com",
  "bonefish grill": "bonefishgrill.com",
  "booking.com": "booking.com",
  "boost mobile select retailer": "boostmobile.com",
  "bose": "bose.com",
  "boston college": "bc.edu",
  "boston consulting group": "bcg.com",
  "boston scientific": "bostonscientific.com",
  "boston university": "bu.edu",
  "bottega veneta": "bottegaveneta.com",
  "box": "box.com",
  "boxed": "boxed.com",
  "bp": "bp.com",
  "breitling": "breitling.com",
  "brex": "brex.com",
  "brigham young university": "byu.edu",
  "bristol myers squibb": "bms.com",
  "britbox international": "britbox.com",
  "british airways holidays": "ba.com",
  "broadcom": "broadcom.com",
  "brookfield": "brookfield.com",
  "brooks": "brooksrunning.com",
  "brooks brothers": "brooksbrothers.com",
  "brown university": "brown.edu",
  "bt": "bt.com",
  "bubly sparkling water": "bubly.com",
  "bud light": "budlight.com",
  "budget car rental": "budget.com",
  "budweiser": "budweiser.com",
  "buffalo bills": "buffalobills.com",
  "buffalo wild wings": "buffalowildwings.com",
  "bugatti": "bugatti.com",
  "buick": "buick.com",
  "bulgari": "bulgari.com",
  "burberry": "burberry.com",
  "burger king": "bk.com",
  "business insider": "businessinsider.com",
  "buzzfeed": "buzzfeed.com",
  "byd": "byd.com",
  "bytedance": "bytedance.com",
  "cadillac": "cadillac.com",
  "caltech": "caltech.edu",
  "calvin klein": "calvinklein.com",
  "cambridge": "cam.ac.uk",
  "campbell shop": "campbells.com",
  "canon": "canon.com",
  "canva": "canva.com",
  "canva pro": "canva.com",
  "capcom": "capcom.com",
  "capital one": "capitalone.com",
  "captain morgan": "captainmorgan.com",
  "cargill": "cargill.com",
  "carhartt": "carhartt.com",
  "carl&#x27;s jr.": "carlsjr.com",
  "carlsberg": "carlsberg.com",
  "carnegie mellon university": "cmu.edu",
  "carnival cruise line": "carnival.com",
  "carrabba": "carrabbas.com",
  "carta": "carta.com",
  "cartier": "cartier.com",
  "carvana": "carvana.com",
  "cash app": "cash.app",
  "caterpillar": "caterpillar.com",
  "cathay pacific": "cathaypacific.com",
  "cava": "cava.com",
  "caviar,": "trycaviar.com",
  "cboe global markets": "cboe.com",
  "cbs news": "cbsnews.com",
  "cd projekt red": "cdprojektred.com",
  "celebrity cruises": "celebritycruises.com",
  "celine": "celine.com",
  "celsius": "celsius.com",
  "centene": "centene.com",
  "cepheid": "cepheid.com",
  "cerebras": "cerebras.net",
  "chanel": "chanel.com",
  "changs": "pfchangs.com",
  "character": "character.ai",
  "charles schwab": "aboutschwab.com",
  "chase": "chase.com",
  "chatgpt": "openai.com",
  "chatgpt plus": "openai.com",
  "cheapflights media": "cheapflights.com",
  "cheapoair": "cheapoair.com",
  "check point software": "checkpoint.com",
  "checkers and rallys": "checkers.com",
  "checkout.com": "checkout.com",
  "cheddar": "cheddars.com",
  "chevrolet": "chevrolet.com",
  "chevron": "chevron.com",
  "chewy": "chewy.com",
  "chicago bears": "chicagobears.com",
  "chick-fil-a": "chick-fil-a.com",
  "chiefs": "chiefs.com",
  "chime": "chime.com",
  "china mobile": "chinamobileltd.com",
  "china southern airlines": "csair.com",
  "chipotle": "chipotle.com",
  "chobani": "chobani.com",
  "choice hotels international": "choicehotels.com",
  "chroma": "trychroma.com",
  "chrysler": "chrysler.com",
  "chubb": "chubb.com",
  "cigna healthcare": "cigna.com",
  "cincinnati bengals": "bengals.com",
  "cisco": "cisco.com",
  "citi": "citi.com",
  "citigroup": "citigroup.com",
  "citizens bank": "citizensbank.com",
  "citroën": "citroen.com",
  "clarks": "clarks.com",
  "claude": "anthropic.com",
  "claude ai": "claude.ai",
  "clemson university": "clemson.edu",
  "cleveland browns": "clevelandbrowns.com",
  "cleveland clinic": "clevelandclinic.org",
  "cloudflare": "cloudflare.com",
  "clubhouse": "clubhouse.com",
  "cme": "cmegroup.com",
  "cnbc": "cnbc.com",
  "cnn": "cnn.com",
  "coach": "coach.com",
  "coca cola": "cocacola.com",
  "coca-cola": "coca-cola.com",
  "cognition ai": "cognition.ai",
  "cohere": "cohere.com",
  "coinbase": "coinbase.com",
  "cole haan": "colehaan.com",
  "colgate-palmolive": "colgatepalmolive.com",
  "columbia": "columbia.edu",
  "columbia sportswear": "columbia.com",
  "columbia university": "columbia.edu",
  "comerica": "comerica.com",
  "commbank": "commbank.com.au",
  "commerzbank": "commerzbank.com",
  "conagra brands": "conagrabrands.com",
  "confluent": "confluent.io",
  "contextual ai": "contextual.ai",
  "converse": "converse.com",
  "copilot": "microsoft.com",
  "coreweave": "coreweave.com",
  "cornell": "cornell.edu",
  "cornell university": "cornell.edu",
  "corona": "coronaextra.com",
  "corsair": "corsair.com",
  "cos thailand": "cosstores.com",
  "costco": "costco.com",
  "coupang": "coupang.com",
  "cowboys": "dallascowboys.com",
  "cox communications": "cox.com",
  "cracker barrel old country store": "crackerbarrel.com",
  "crackle": "crackle.com",
  "cricket wireless": "cricketwireless.com",
  "crocs": "crocs.com",
  "crowdstrike": "crowdstrike.com",
  "crunchy roll": "crunchyroll.com",
  "crunchyroll": "crunchyroll.com",
  "crypto.com": "crypto.com",
  "crédit agricole": "credit-agricole.com",
  "culver": "culvers.com",
  "cupra": "cupra.com",
  "curiosity inc": "curiositystream.com",
  "cursor": "cursor.com",
  "cvs health": "cvshealth.com",
  "cvs pharmacy": "cvs.com",
  "cyberark": "cyberark.com",
  "cybereason": "cybereason.com",
  "dailymail": "dailymail.co.uk",
  "dairy queen": "dairyqueen.com",
  "dallas cowboys": "dallascowboys.com",
  "danaher": "danaher.com",
  "danone": "danone.com",
  "danske bank": "danskebank.com",
  "darktrace": "darktrace.com",
  "dartmouth college": "dartmouth.edu",
  "databricks": "databricks.com",
  "datadog": "datadog.com",
  "dave": "dave.com",
  "dazn": "dazn.com",
  "dbs": "dbs.com",
  "deel": "deel.com",
  "deepseek": "deepseek.com",
  "deezer": "deezer.com",
  "del taco": "deltaco.com",
  "deliveroo": "deliveroo.co.uk",
  "delivery hero": "deliveryhero.com",
  "dell": "dell.com",
  "deloitte": "deloitte.com",
  "delta air lines": "delta.com",
  "dennys": "dennys.com",
  "denver broncos": "denverbroncos.com",
  "depop": "depop.com",
  "detroit lions": "detroitlions.com",
  "deutsche bank": "db.com",
  "dhl": "dhl.com",
  "diesel": "diesel.com",
  "digitalocean": "digitalocean.com",
  "dior": "dior.com",
  "discord": "discord.com",
  "discover": "discover.com",
  "discovery": "discoveryplus.com",
  "discovery plus": "discoveryplus.com",
  "discovery+": "discoveryplus.com",
  "disney": "disneyplus.com",
  "disney plus": "disneyplus.com",
  "disney+": "disneyplus.com",
  "docker": "docker.com",
  "dodge": "dodge.com",
  "dolce &amp; gabbana": "dolcegabbana.com",
  "dolphins": "miamidolphins.com",
  "dominos": "dominos.com",
  "doordash": "doordash.com",
  "dow": "dow.com",
  "doximity": "doximity.com",
  "dr pepper": "drpepper.com",
  "dr. martens": "drmartens.com",
  "dropbox": "dropbox.com",
  "duke university": "duke.edu",
  "dunkin&#x27;": "dunkindonuts.com",
  "duo security": "duo.com",
  "dupont": "dupont.com",
  "dutch bros coffee": "dutchbros.com",
  "dynatrace": "dynatrace.com",
  "dyson": "dyson.com",
  "e*trade": "us.etrade.com",
  "easyjet": "easyjet.com",
  "ebay": "ebay.com",
  "ecco": "ecco.com",
  "edward jones": "edwardjones.com",
  "edwards lifesciences": "edwards.com",
  "ee": "ee.co.uk",
  "elastic": "elastic.co",
  "electronic arts": "ea.com",
  "elevance health": "elevancehealth.com",
  "elevenlabs": "elevenlabs.io",
  "eli lilly and company": "lilly.com",
  "emerson": "emerson.com",
  "emirates": "emirates.com",
  "emirates nbd": "emiratesnbd.com",
  "emory university": "emory.edu",
  "engadget": "engadget.com",
  "enterprise": "enterprise.com",
  "envato": "elements.envato.com",
  "envato elements": "elements.envato.com",
  "epic": "epicgames.com",
  "epic games": "epicgames.com",
  "epic on": "epicon.in",
  "epic systems": "epic.com",
  "equifax": "equifax.com",
  "erie insurance": "erieinsurance.com",
  "eros now": "erosnow.com",
  "eset": "eset.com",
  "espn": "espn.com",
  "eth zürich": "ethz.ch",
  "etihad": "etihad.com",
  "etsy": "etsy.com",
  "everlane": "everlane.com",
  "everyplate": "everyplate.com",
  "evian": "evian.com",
  "expedia": "expedia.com",
  "expensify": "expensify.com",
  "experian": "experian.com",
  "express": "express.com",
  "express scripts": "express-scripts.com",
  "express vpn": "expressvpn.com",
  "expressvpn": "expressvpn.com",
  "exxonmobil": "corporate.exxonmobil.com",
  "ey": "ey.com",
  "facebook": "facebook.com",
  "factor": "factor75.com",
  "faire": "faire.com",
  "fairmont hotels": "fairmont.com",
  "farfetch": "farfetch.com",
  "farmers insurance": "farmers.com",
  "fastly": "fastly.com",
  "fedex": "fedex.com",
  "fendi": "fendi.com",
  "ferragamo": "ferragamo.com",
  "ferrari": "ferrari.com",
  "fiat": "fiat.com",
  "fidelity investments": "fidelity.com",
  "fifth third bank": "53.com",
  "figma": "figma.com",
  "figure": "figure.com",
  "fiji water": "fijiwater.com",
  "financial times": "ft.com",
  "finnair": "finnair.com",
  "firehouse subs": "firehousesubs.com",
  "fireworks ai": "fireworks.ai",
  "first citizens bank": "firstcitizens.com",
  "fis": "fisglobal.com",
  "fisker": "fiskerinc.com",
  "five guys": "fiveguys.com",
  "flighthub": "flighthub.com",
  "flipkart": "flipkart.com",
  "florida state university": "fsu.edu",
  "forbes": "forbes.com",
  "forcepoint": "forcepoint.com",
  "ford": "ford.com",
  "fortinet": "fortinet.com",
  "fossil": "fossil.com",
  "four seasons hotels and resorts": "fourseasons.com",
  "fox news": "foxnews.com",
  "framer": "framer.com",
  "franklin templeton": "franklintempleton.com",
  "free people": "freepeople.com",
  "fresenius": "fresenius.com",
  "freshdirect": "freshdirect.com",
  "freshworks": "freshworks.com",
  "frito-lay": "fritolay.com",
  "frontier airlines": "flyfrontier.com",
  "frontier communications": "frontier.com",
  "fubotv": "fubo.tv",
  "gap": "gap.com",
  "gatorade": "gatorade.com",
  "ge healthcare": "gehealthcare.com",
  "geely auto": "geely.com",
  "geico": "geico.com",
  "gemini": "gemini.com",
  "general dynamics": "gd.com",
  "general electric": "ge.com",
  "general mills": "generalmills.com",
  "general motors": "gm.com",
  "generali": "generali.com",
  "genesis": "genesis.com",
  "georgetown university": "georgetown.edu",
  "georgia institute of technology": "gatech.edu",
  "getyourguide": "getyourguide.com",
  "ghirardelli": "ghirardelli.com",
  "gilead sciences": "gilead.com",
  "github": "github.com",
  "gitlab": "gitlab.com",
  "givenchy": "givenchy.com",
  "gizmodo": "gizmodo.com",
  "glean": "glean.com",
  "gmc": "gmc.com",
  "goat": "goat.com",
  "gog.com": "gog.com",
  "going": "going.com",
  "goldman sachs": "goldmansachs.com",
  "goodrx": "goodrx.com",
  "google": "google.com",
  "google deepmind": "deepmind.com",
  "google one": "one.google.com",
  "gopuff": "gopuff.com",
  "gousto": "gousto.co.uk",
  "goyard": "goyard.com",
  "grailed": "grailed.com",
  "grammarly": "grammarly.com",
  "greenlight": "greenlightcard.com",
  "grok": "x.ai",
  "grok ai": "x.ai",
  "groq": "groq.com",
  "groupon": "groupon.com",
  "grubhub": "grubhub.com",
  "gsk": "gsk.com",
  "guardian life": "guardianlife.com",
  "gucci": "gucci.com",
  "guess": "guess.com",
  "guinness": "guinness.com",
  "gusto": "gusto.com",
  "gymshark": "gymshark.com",
  "hackerone": "hackerone.com",
  "hanes": "hanes.com",
  "hardees": "hardees.com",
  "harrods": "harrods.com",
  "harry winston": "harrywinston.com",
  "harvard": "harvard.edu",
  "harvard university": "harvard.edu",
  "harvey": "harvey.ai",
  "hashicorp": "hashicorp.com",
  "hawaiian airlines": "hawaiianairlines.com",
  "hbo": "hbomax.com",
  "hbo max": "hbomax.com",
  "hca healthcare": "hcahealthcare.com",
  "heineken": "heineken.com",
  "heinz sales co": "heinz.com",
  "hellmann&#x27;s": "hellmanns.com",
  "hellofresh": "hellofresh.com",
  "hennessy": "hennessy.com",
  "hermès": "hermes.com",
  "hertz": "hertz.com",
  "hewlett packard enterprise": "hpe.com",
  "heydude": "heydude.com",
  "hielan management": "chilis.com",
  "hilton": "hilton.com",
  "hims": "forhims.com",
  "hippo insurance": "hippo.com",
  "hm": "hm.com",
  "hoichoi": "hoichoi.tv",
  "hoichoi tv": "hoichoi.tv",
  "hoka": "hoka.com",
  "holiday inn": "holidayinn.com",
  "holland america line": "hollandamerica.com",
  "home chef": "homechef.com",
  "honda": "honda.com",
  "honeywell": "honeywell.com",
  "hoopla digital": "hoopladigital.com",
  "hooters": "hooters.com",
  "hopper": "hopper.com",
  "hostelworld group": "hostelworld.com",
  "hotels.com": "hotels.com",
  "hotwire": "hotwire.com",
  "houston texans": "houstontexans.com",
  "hoyoverse": "hoyoverse.com",
  "hp": "hp.com",
  "hsbc": "hsbc.com",
  "hublot": "hublot.com",
  "hubspot": "hubspot.com",
  "huffpost": "huffpost.com",
  "hugging face": "huggingface.co",
  "hugo boss": "hugoboss.com",
  "hulu": "hulu.com",
  "humana": "humana.com",
  "huntington bank": "huntington.com",
  "hush puppies": "hushpuppies.com",
  "hyatt": "hyatt.com",
  "hyperx systems llc": "hyperx.com",
  "hyundai": "hyundai.com",
  "hyundai motor america": "hyundaiusa.com",
  "häagen-dazs": "haagendazs.com",
  "iberia": "iberia.com",
  "ibm": "ibm.com",
  "icici bank": "icicibank.com",
  "ihg hotels &amp; resorts": "ihg.com",
  "ihop": "ihop.com",
  "ikea": "ikea.com",
  "in-n-out burger": "in-n-out.com",
  "indiana university": "indiana.edu",
  "indianapolis colts": "colts.com",
  "indigo (interglobe aviation ltd)": "goindigo.in",
  "infiniti": "infinitiusa.com",
  "inflection ai": "inflection.ai",
  "ing": "ing.com",
  "instacart": "instacart.com",
  "instagram": "instagram.com",
  "intel": "intel.com",
  "interactive brokers": "interactivebrokers.com",
  "intercom": "intercom.com",
  "intercontinental exchange": "theice.com",
  "intuitive surgical": "intuitive.com",
  "invesco": "invesco.com",
  "iowa state university": "iastate.edu",
  "iptv": "iptvsmarters.com",
  "isuzu north america": "isuzu.com",
  "itaú": "itau.com.br",
  "itch": "itch.io",
  "iwc schaffhausen": "iwc.com",
  "j.crew": "jcrew.com",
  "j.p. morgan": "jpmorgan.com",
  "jack daniel distillery": "jackdaniels.com",
  "jack in the box": "jackinthebox.com",
  "jacksonville jaguars": "jaguars.com",
  "jaeger-lecoultre": "jaeger-lecoultre.com",
  "jaguar": "jaguar.com",
  "jameson distillery bow st": "jamesonwhiskey.com",
  "japan airlines": "jal.com",
  "jasper": "jasper.ai",
  "jeep": "jeep.com",
  "jefferies": "jefferies.com",
  "jersey mike&#x27;s": "jerseymikes.com",
  "jetblue": "jetblue.com",
  "jetbrains": "jetbrains.com",
  "jets": "newyorkjets.com",
  "jimmy john&#x27;s": "jimmyjohns.com",
  "jio": "jiocinema.com",
  "jio hotstar": "jiohotstar.com",
  "jiocinema": "jiocinema.com",
  "john deere": "deere.com",
  "johnnie walker": "johnniewalker.com",
  "johns hopkins university": "jhu.edu",
  "johnson &amp; johnson": "jnj.com",
  "jpmorgan chase &amp;": "jpmorganchase.com",
  "just eat takeaway": "justeattakeaway.com",
  "jägermeister gästehaus": "jagermeister.com",
  "kaiser permanente": "healthy.kaiserpermanente.org",
  "kanopy": "kanopy.com",
  "kansas city chiefs": "chiefs.com",
  "kaspersky": "kaspersky.com",
  "kate spade new york": "katespade.com",
  "keen": "keenfootwear.com",
  "kellanova": "kellanova.com",
  "kelloggs": "kelloggs.com",
  "keurig": "keurig.com",
  "keybank": "key.com",
  "kfc": "kfc.com",
  "kia": "kia.com",
  "kick": "kick.com",
  "kimberly-clark": "kimberly-clark.com",
  "kimpton da an hotel 金普頓大安酒店": "kimptonhotels.com",
  "kit kat": "kitkat.com",
  "kith": "kith.com",
  "kiwi.com": "kiwi.com",
  "kkr": "kkr.com",
  "klarna": "klarna.com",
  "klm": "klm.com",
  "klook travel": "klook.com",
  "knowbe4": "knowbe4.com",
  "koenigsegg": "koenigsegg.com",
  "kohls": "kohls.com",
  "konami digital entertainment": "konami.com",
  "korean air": "koreanair.com",
  "kpmg": "kpmg.com",
  "kroger": "kroger.com",
  "lacoste": "lacoste.com",
  "lacroix": "lacroixwater.com",
  "lambda": "lambdalabs.com",
  "lamborghini": "lamborghini.com",
  "land rover": "landrover.com",
  "lands&#x27; end": "landsend.com",
  "langchain": "langchain.com",
  "lastminute": "lastminute.com",
  "latam airlines": "latam.com",
  "lavazza": "lavazza.com",
  "lazard": "lazard.com",
  "legoland": "legoland.com",
  "lego®": "lego.com",
  "lemon8": "lemon8-app.com",
  "lemonade": "lemonade.com",
  "lendingclub": "lendingclub.com",
  "lenovo": "lenovo.com",
  "levi": "levi.com",
  "lexus": "lexus.com",
  "lg": "lg.com",
  "li auto": "lixiang.com",
  "liberty mutual": "libertymutualgroup.com",
  "lic": "licindia.in",
  "lincoln financial group": "lincolnfinancial.com",
  "lincoln motor company": "lincoln.com",
  "lindt": "lindt.com",
  "line": "line.me",
  "linear": "linear.app",
  "linkedin": "linkedin.com",
  "linkedin premium": "linkedin.com",
  "lionsgate": "lionsgateplay.com",
  "lionsgate play": "lionsgateplay.com",
  "lipton": "lipton.com",
  "liquid death": "liquiddeath.com",
  "little caesars pizza": "littlecaesars.com",
  "llamaindex": "llamaindex.ai",
  "lloyds bank": "lloydsbank.com",
  "lockheed martin": "lockheedmartin.com",
  "loewe": "loewe.com",
  "logitech g": "logitechg.com",
  "longhorn steakhouse": "longhornsteakhouse.com",
  "lookout": "lookout.com",
  "los angeles chargers": "chargers.com",
  "lotus": "lotuscars.com",
  "louis vuitton": "louisvuitton.com",
  "louisiana state university": "lsu.edu",
  "lowe’s home improvement": "lowes.com",
  "lucid motors": "lucidmotors.com",
  "lufthansa": "lufthansa.com",
  "lululemon": "lululemon.com",
  "luma ai": "lumalabs.ai",
  "lumen technologies": "lumen.com",
  "m&amp;t bank": "mtb.com",
  "m1": "m1.com",
  "macy&#x27;s": "macys.com",
  "madewell": "madewell.com",
  "magic": "magic.dev",
  "mahindra group": "mahindra.com",
  "malaysia airlines": "malaysiaairlines.com",
  "malwarebytes": "malwarebytes.com",
  "mandarin oriental hotel group": "mandarinoriental.com",
  "mango": "mango.com",
  "manulife": "manulife.com",
  "markel": "markel.com",
  "marley spoon": "marleyspoon.com",
  "marqeta": "marqeta.com",
  "marriott international": "marriott.com",
  "mars": "mars.com",
  "maserati": "maserati.com",
  "mashable": "mashable.com",
  "mass general brigham": "massgeneralbrigham.org",
  "massachusetts institute of technology": "mit.edu",
  "massmutual": "massmutual.com",
  "master francesco sa": "msccruises.com",
  "mastercard": "mastercard.com",
  "mastodon": "mastodon.social",
  "max": "max.com",
  "mayo clinic": "mayoclinic.org",
  "mazda motor corporation": "mazda.com",
  "mcafee": "mcafee.com",
  "mcdonald": "mcdonalds.com",
  "mcdonald&#x27;s": "mcdonalds.com",
  "mcgill university": "mcgill.ca",
  "mckesson": "mckesson.com",
  "mckinsey &amp; company": "mckinsey.com",
  "mclaren racing": "mclaren.com",
  "medium": "medium.com",
  "medtronic": "medtronic.com",
  "melio": "meliopayments.com",
  "mercado libre": "mercadolibre.com",
  "mercari": "mercari.com",
  "mercedes": "mercedes-benz.com",
  "mercedes-benz": "mercedes-benz.com",
  "merck": "merck.com",
  "mercury": "mercury.com",
  "mercury insurance": "mercuryinsurance.com",
  "merrell": "merrell.com",
  "meta": "meta.com",
  "meta platforms": "meta.com",
  "metlife": "metlife.com",
  "mgm resorts international": "mgmresorts.com",
  "miami dolphins": "miamidolphins.com",
  "michael kors": "michaelkors.com",
  "michigan state university": "msu.edu",
  "micron technology": "micron.com",
  "microsoft": "microsoft.com",
  "microsoft copilot": "microsoft.com",
  "midjourney": "midjourney.com",
  "miller lite": "millerlite.com",
  "minecraft": "minecraft.net",
  "mini": "mini.com",
  "mint mobile": "mintmobile.com",
  "minted": "minted.com",
  "miro": "miro.com",
  "mississippi state university": "msstate.edu",
  "mistral ai": "mistral.ai",
  "mit": "mit.edu",
  "mitsubishi motors north america": "mitsubishicars.com",
  "mixpanel": "mixpanel.com",
  "mizuho financial": "mizuhogroup.com",
  "mizuno": "mizunousa.com",
  "mms": "mms.com",
  "modal labs": "modal.com",
  "modelo beer": "modelousa.com",
  "moderna": "modernatx.com",
  "molina healthcare": "molinahealthcare.com",
  "momondo": "momondo.com",
  "moncler": "moncler.com",
  "monday": "monday.com",
  "mondelēz international": "mondelezinternational.com",
  "moneygram": "moneygram.com",
  "mongodb": "mongodb.com",
  "monster energy": "monsterenergy.com",
  "montblanc": "montblanc.com",
  "monzo": "monzo.com",
  "moodys": "moodys.com",
  "morgan stanley": "morganstanley.com",
  "mount sinai health system": "mountsinai.org",
  "mountain": "mountaindew.com",
  "ms now": "msnbc.com",
  "mubi": "mubi.com",
  "munich re": "munichre.com",
  "n26": "n26.com",
  "nab": "nab.com.au",
  "nando": "nandos.com",
  "nasdaq": "nasdaq.com",
  "national car rental": "nationalcar.com",
  "nationwide": "nationwide.com",
  "natwest": "natwest.com",
  "naughty dog": "naughtydog.com",
  "navy federal credit union": "navyfederal.org",
  "nbc news": "nbcnews.com",
  "nescafé méxico": "nescafe.com",
  "nespresso": "nespresso.com",
  "nestlé": "nestle.com",
  "netflix": "netflix.com",
  "netlify": "netlify.com",
  "netskope": "netskope.com",
  "new balance": "newbalance.com",
  "new orleans saints": "neworleanssaints.com",
  "new york giants": "giants.com",
  "new york jets": "newyorkjets.com",
  "new york life insurance company": "newyorklife.com",
  "new york university": "nyu.edu",
  "newegg": "newegg.com",
  "newsweek": "newsweek.com",
  "nextdoor": "nextdoor.com",
  "nfl": "nfl.com",
  "nike": "nike.com",
  "nintendo": "nintendo.com",
  "nio": "nio.com",
  "nissan": "nissan-global.com",
  "nissan usa": "nissanusa.com",
  "nomura holdings": "nomura.com",
  "nord": "nordvpn.com",
  "nord security": "nordsecurity.com",
  "nordea": "nordea.com",
  "nordstrom": "nordstrom.com",
  "nordvpn": "nordvpn.com",
  "northeastern university": "northeastern.edu",
  "northrop grumman": "northropgrumman.com",
  "northwestern mutual": "northwesternmutual.com",
  "northwestern university": "northwestern.edu",
  "norwegian cruise line": "ncl.com",
  "notion": "notion.so",
  "novartis": "novartis.com",
  "novo nordisk": "novonordisk.com",
  "npr": "npr.org",
  "nubank": "nubank.com.br",
  "nuvei": "nuvei.com",
  "nvidia": "nvidia.com",
  "nykaa": "nykaa.com",
  "nyse": "nyse.com",
  "o2": "o2.co.uk",
  "oakley": "oakley.com",
  "oatly": "oatly.com",
  "ocbc bank": "ocbc.com",
  "ocean spray": "oceanspray.com",
  "office depot officemax": "officedepot.com",
  "okta": "okta.com",
  "olive garden": "olivegarden.com",
  "omega": "omegawatches.com",
  "omio": "omio.com",
  "on": "on.com",
  "onitsuka tiger": "onitsukatiger.com",
  "onlyfans": "onlyfans.com",
  "opel": "opel.com",
  "openai": "openai.com",
  "oracle": "oracle.com",
  "orange": "orange.com",
  "orbitz": "orbitz.com",
  "oreo": "oreo.com",
  "oscar": "hioscar.com",
  "ott": "netflix.com",
  "otto": "otto.de",
  "outback steakhouse": "outback.com",
  "overstock": "overstock.com",
  "oxford": "ox.ac.uk",
  "ozon": "ozon.ru",
  "packers": "packers.com",
  "pagani automobili": "pagani.com",
  "pagerduty": "pagerduty.com",
  "palantir technologies": "palantir.com",
  "palo alto networks": "paloaltonetworks.com",
  "panasonic north america": "panasonic.com",
  "panda express": "pandaexpress.com",
  "pandora": "pandora.com",
  "panera bread": "panera.com",
  "panerai": "panerai.com",
  "panthers": "panthers.com",
  "papa johns": "papajohns.com",
  "paramount": "paramountplus.com",
  "paramount plus": "paramountplus.com",
  "paramount+": "paramountplus.com",
  "patagonia": "patagonia.com",
  "patek philippe": "patek.com",
  "patreon": "patreon.com",
  "patriots": "patriots.com",
  "patrón": "patron.com",
  "payoneer": "payoneer.com",
  "paypal": "paypal.com",
  "paytm": "paytm.com",
  "peacock": "peacocktv.com",
  "peet&#x27;s coffee": "peets.com",
  "peloton interactive": "onepeloton.com",
  "pepsi": "pepsi.com",
  "pepsico": "pepsico.com",
  "perplexity": "perplexity.ai",
  "perplexity ai": "perplexity.ai",
  "perrier": "perrier.com",
  "peugeot": "peugeot.com",
  "pfizer": "pfizer.com",
  "philadelphia eagles": "philadelphiaeagles.com",
  "philips": "philips.com",
  "philo": "philo.com",
  "picsart": "picsart.com",
  "picsart pro": "picsart.com",
  "pika": "pika.art",
  "pinecone": "pinecone.io",
  "ping identity": "pingidentity.com",
  "pinterest": "pinterest.com",
  "pizza hut": "pizzahut.com",
  "plaid": "plaid.com",
  "playstation": "playstation.com",
  "plex": "plex.tv",
  "pluto tv": "pluto.tv",
  "pnc": "pnc.com",
  "poland spring": "polandspring.com",
  "polestar": "polestar.com",
  "policygenius": "policygenius.com",
  "politico": "politico.com",
  "poolside": "poolside.ai",
  "popeyes": "popeyes.com",
  "porsche": "porsche.com",
  "poshmark": "poshmark.com",
  "post holdings": "postholdings.com",
  "postman": "postman.com",
  "postmates": "postmates.com",
  "pottery barn": "potterybarn.com",
  "powerade": "powerade.com",
  "prada": "prada.com",
  "priceline": "priceline.com",
  "prime": "primevideo.com",
  "prime video": "primevideo.com",
  "princess cruises": "princess.com",
  "princeton": "princeton.edu",
  "princeton university": "princeton.edu",
  "procter &amp; gamble": "pg.com",
  "progressive insurance": "progressive.com",
  "proofpoint": "proofpoint.com",
  "propublica": "propublica.org",
  "prudential financial": "prudential.com",
  "public": "public.com",
  "puck": "puck.news",
  "puma": "puma.com",
  "purdue university": "purdue.edu",
  "pwc": "pwc.com",
  "qantas": "qantas.com",
  "qatar airways": "qatarairways.com",
  "qdoba restaurant corporation": "qdoba.com",
  "qnb group": "qnb.com",
  "quaker oats beverage company": "quakeroats.com",
  "qualcomm": "qualcomm.com",
  "qualys": "qualys.com",
  "quince": "quince.com",
  "quora": "quora.com",
  "qxl": "allegro.pl",
  "radisson blu": "radissonhotels.com",
  "raiders": "raiders.com",
  "raising canes": "raisingcanes.com",
  "rakuten": "rakuten.com",
  "ralph lauren": "ralphlauren.com",
  "ram": "ramtrucks.com",
  "ramp": "ramp.com",
  "rams": "therams.com",
  "rapid7": "rapid7.com",
  "rapyd": "rapyd.com",
  "raymond james financial": "raymondjames.com",
  "razer": "razer.com",
  "razorpay": "razorpay.com",
  "recorded future": "recordedfuture.com",
  "red bull": "redbull.com",
  "red lobster": "redlobster.com",
  "red robin": "redrobin.com",
  "reddit": "reddit.com",
  "reebok": "reebok.com",
  "reformation": "thereformation.com",
  "regeneron pharmaceuticals": "regeneron.com",
  "regions bank": "regions.com",
  "remitly": "remitly.com",
  "renault": "renault.com",
  "rentalcars": "rentalcars.com",
  "replicate": "replicate.com",
  "replit": "replit.com",
  "retool": "retool.com",
  "reuters": "reuters.com",
  "reverb": "reverb.com",
  "revolut": "revolut.com",
  "rice university": "rice.edu",
  "rimac seguros y reaseguros": "rimac.com",
  "riot games": "riotgames.com",
  "ripple": "ripple.com",
  "rippling": "rippling.com",
  "ritz-carlton": "ritzcarlton.com",
  "rivian": "rivian.com",
  "ro": "ro.co",
  "robinhood markets": "robinhood.com",
  "roblox": "roblox.com",
  "roche": "roche.com",
  "rockstar energy drink": "rockstarenergy.com",
  "rockstar games": "rockstargames.com",
  "rogers": "rogers.com",
  "roku": "roku.com",
  "rolex": "rolex.com",
  "rolls": "rolls-roycemotorcars.com",
  "rome2rio": "rome2rio.com",
  "rover": "rover.com",
  "rovio entertainment corporation": "rovio.com",
  "royal bank of canada": "rbc.com",
  "royal caribbean international": "royalcaribbean.com",
  "rtx": "rtx.com",
  "rubrik": "rubrik.com",
  "rumble": "rumble.com",
  "runway": "runwayml.com",
  "rutgers university": "rutgers.edu",
  "ryanair": "ryanair.com",
  "s&amp;p global": "spglobal.com",
  "s.pellegrino": "sanpellegrino.com",
  "safeway": "safeway.com",
  "saint laurent": "ysl.com",
  "salesforce": "salesforce.com",
  "salomon": "salomon.com",
  "sambanova systems": "sambanova.ai",
  "samsung": "samsung.com",
  "samsung electronics": "samsung.com",
  "san francisco 49ers": "49ers.com",
  "sanofi": "sanofi.com",
  "santander bank": "santanderbank.com",
  "sap": "sap.com",
  "sap concur": "concur.com",
  "saucony": "saucony.com",
  "scale ai": "scale.com",
  "schweppes": "schweppes.com",
  "scotiabank": "scotiabank.com",
  "seamless": "seamless.com",
  "seat": "seat.com",
  "seattle seahawks": "seahawks.com",
  "seaworld parks": "seaworld.com",
  "sega of america": "sega.com",
  "semafor": "semafor.com",
  "sentinelone": "sentinelone.com",
  "sentry": "sentry.io",
  "sephora": "sephora.com",
  "server": "digitalocean.com",
  "servicenow": "servicenow.com",
  "shake shack": "shakeshack.com",
  "shein": "shein.com",
  "shell plc": "shell.com",
  "shipt": "shipt.com",
  "shopee": "shopee.com",
  "shopify": "shopify.com",
  "showtime networks": "showtime.com",
  "shudder": "shudder.com",
  "siemens": "siemens.com",
  "siemens healthineers": "siemens-healthineers.com",
  "sierra": "sierra.ai",
  "signal": "signal.org",
  "silicon valley bank": "svb.com",
  "singapore airlines": "singaporeair.com",
  "siriusxm": "siriusxm.com",
  "site59.com": "travelocity.com",
  "six flags": "sixflags.com",
  "six senses hotels resorts spas": "sixsenses.com",
  "sixt": "sixt.com",
  "skechers": "skechers.com",
  "skims": "skims.com",
  "skyscanner": "skyscanner.com",
  "slack": "slack.com",
  "sling tv": "sling.com",
  "smart": "smart.com",
  "smirnoff ice": "smirnoff.com",
  "snapchat": "snapchat.com",
  "snapple beverage corp": "snapple.com",
  "snowflake": "snowflake.com",
  "snyk": "snyk.io",
  "société générale": "societegenerale.com",
  "sofi": "sofi.com",
  "softbank": "softbank.jp",
  "sonic drive-in": "sonicdrivein.com",
  "sony": "sonyliv.com",
  "sony liv": "sonyliv.com",
  "sonyliv": "sonyliv.com",
  "sophos": "sophos.com",
  "soundcloud": "soundcloud.com",
  "southern methodist university": "smu.edu",
  "southwest airlines": "southwest.com",
  "spectrum": "spectrum.com",
  "sperry": "sperry.com",
  "splunk": "splunk.com",
  "spotify": "spotify.com",
  "spotify premium": "spotify.com",
  "square": "squareup.com",
  "square enix": "square-enix.com",
  "stability ai": "stability.ai",
  "stack overflow": "stackoverflow.com",
  "standard bank group": "standardbank.com",
  "standard chartered": "sc.com",
  "stanford": "stanford.edu",
  "stanford university": "stanford.edu",
  "staples": "staples.com",
  "starbucks": "starbucks.com",
  "starbucks coffee company": "starbucks.com",
  "starz": "starz.com",
  "state farm": "statefarm.com",
  "state street": "statestreet.com",
  "steam": "steampowered.com",
  "steelers": "steelers.com",
  "steelseries": "steelseries.com",
  "stella artois": "stellaartois.com",
  "steve madden": "stevemadden.com",
  "stockx": "stockx.com",
  "stream server": "plex.tv",
  "stripe": "stripe.com",
  "stryker": "stryker.com",
  "subaru of america": "subaru.com",
  "substack": "substack.com",
  "subway": "subway.com",
  "sumitomo mitsui banking corporation – smbc": "smfg.co.jp",
  "sumo logic": "sumologic.com",
  "sun life": "sunlife.com",
  "sun nxt": "sunnxt.com",
  "suncorp": "suncorp.com.au",
  "sunnxt": "sunnxt.com",
  "suno ai": "suno.com",
  "supabase": "supabase.com",
  "supercell": "supercell.com",
  "surfshark": "surfshark.com",
  "surfshark vpn": "surfshark.com",
  "suzuki motor of america": "suzuki.com",
  "sweetgreen": "sweetgreen.com",
  "swiggy": "swiggy.com",
  "swiss international air lines": "swiss.com",
  "swiss re": "swissre.com",
  "synchrony bank credit card services": "synchronybank.com",
  "synthesia": "synthesia.io",
  "syracuse university": "syracuse.edu",
  "t-mobile": "t-mobile.com",
  "t. rowe price": "troweprice.com",
  "taco bell": "tacobell.com",
  "tag heuer": "tagheuer.com",
  "taiwan semiconductor manufacturing company": "tsmc.com",
  "take-two interactive": "take2games.com",
  "takeda pharmaceutical company": "takeda.com",
  "tampa bay buccaneers": "buccaneers.com",
  "tanium": "tanium.com",
  "target": "target.com",
  "tata motors": "tatamotors.com",
  "td bank": "td.com",
  "techcrunch": "techcrunch.com",
  "teladoc health": "teladochealth.com",
  "telefónica": "telefonica.com",
  "telegram": "telegram.org",
  "telegraph": "telegraph.co.uk",
  "telekom": "telekom.com",
  "telstra": "telstra.com.au",
  "telus": "telus.com",
  "temu": "temu.com",
  "tenable": "tenable.com",
  "tencent": "tencent.com",
  "tenet healthcare": "tenethealth.com",
  "tennessee titans": "titansonline.com",
  "tesla": "tesla.com",
  "teva pharmaceuticals": "tevapharm.com",
  "texas a&amp;m university": "tamu.edu",
  "texas christian university": "tcu.edu",
  "texas instruments": "ti.com",
  "texas roadhouse": "texasroadhouse.com",
  "tgi fridays": "tgifridays.com",
  "thai airways international": "thaiairways.com",
  "the atlantic": "theatlantic.com",
  "the carlyle group": "carlyle.com",
  "the cheesecake factory": "thecheesecakefactory.com",
  "the economist": "economist.com",
  "the guardian": "theguardian.com",
  "the hartford": "thehartford.com",
  "the hershey company": "thehersheycompany.com",
  "the hill": "thehill.com",
  "the home depot": "homedepot.com",
  "the independent": "independent.co.uk",
  "the kraft heinz company": "kraftheinzcompany.com",
  "the new york times": "nytimes.com",
  "the new yorker": "newyorker.com",
  "the north face": "thenorthface.com",
  "the ohio state university": "osu.edu",
  "the pennsylvania state university": "psu.edu",
  "the realreal": "therealreal.com",
  "the university of alabama": "ua.edu",
  "the university of chicago": "uchicago.edu",
  "the university of iowa": "uiowa.edu",
  "the university of kansas": "ku.edu",
  "the university of north carolina at chapel hill": "unc.edu",
  "the university of oklahoma": "ou.edu",
  "the university of tennessee system": "tennessee.edu",
  "the university of utah": "utah.edu",
  "the university of virginia": "virginia.edu",
  "the verge": "theverge.com",
  "the wall street journal": "wsj.com",
  "the washington post": "washingtonpost.com",
  "threads": "threads.net",
  "thredup": "thredup.com",
  "tidal": "tidal.com",
  "tiffany &amp;": "tiffany.com",
  "tiktok": "tiktok.com",
  "tim hortons india": "timhortons.com",
  "timberland": "timberland.com",
  "time": "time.com",
  "tipalti": "tipalti.com",
  "toast": "toasttab.com",
  "together ai": "together.ai",
  "tokio marine": "tokiomarine.com",
  "tom ford": "tomford.com",
  "tommy hilfiger": "tommy.com",
  "toms": "toms.com",
  "tory burch": "toryburch.com",
  "totalenergies": "totalenergies.com",
  "toyota": "toyota.com",
  "trader joes": "traderjoes.com",
  "transamerica": "transamerica.com",
  "transport strategy centre at imperial college london": "imperial.ac.uk",
  "transunion": "transunion.com",
  "travelers": "travelers.com",
  "trellix": "trellix.com",
  "trend micro": "trendmicro.com",
  "triller": "triller.co",
  "trip": "trip.com",
  "tripadvisor": "tripadvisor.com",
  "trivago": "trivago.com",
  "tropicana": "tropicana.com",
  "truist bank": "truist.com",
  "truth social": "truthsocial.com",
  "tubi": "tubitv.com",
  "tufts university": "tufts.edu",
  "tumblr": "tumblr.com",
  "turkish airlines": "turkishairlines.com",
  "turo": "turo.com",
  "turtle beach": "turtlebeach.com",
  "twilio": "twilio.com",
  "twinings": "twinings.com",
  "twitch": "twitch.tv",
  "twitter": "twitter.com",
  "tyson foods": "tysonfoods.com",
  "u.s. bank": "usbank.com",
  "uber": "uber.com",
  "uber eats": "ubereats.com",
  "ubisoft": "ubisoft.com",
  "ubs": "ubs.com",
  "ugg": "ugg.com",
  "ullu": "ullu.app",
  "under armour": "underarmour.com",
  "unilever": "unilever.com",
  "uniqlo": "uniqlo.com",
  "united airlines": "united.com",
  "united parcel service": "ups.com",
  "unitedhealth group": "unitedhealth.com",
  "unitedhealthcare": "uhc.com",
  "unity": "unity.com",
  "universal orlando resort": "universalorlando.com",
  "university college london": "ucl.ac.uk",
  "university of arizona": "arizona.edu",
  "university of arkansas": "uark.edu",
  "university of california san diego": "ucsd.edu",
  "university of california, berkeley": "berkeley.edu",
  "university of california, davis": "ucdavis.edu",
  "university of california, irvine": "uci.edu",
  "university of california, los angeles": "ucla.edu",
  "university of california, santa barbara": "ucsb.edu",
  "university of cambridge": "cam.ac.uk",
  "university of colorado boulder": "colorado.edu",
  "university of connecticut": "uconn.edu",
  "university of florida": "ufl.edu",
  "university of georgia": "uga.edu",
  "university of houston": "uh.edu",
  "university of illinois urbana-champaign": "illinois.edu",
  "university of kentucky": "uky.edu",
  "university of maryland, college park": "umd.edu",
  "university of miami": "miami.edu",
  "university of michigan": "umich.edu",
  "university of minnesota twin cities": "umn.edu",
  "university of mississippi": "olemiss.edu",
  "university of missouri": "missouri.edu",
  "university of nebraska–lincoln": "unl.edu",
  "university of notre dame": "nd.edu",
  "university of oregon": "uoregon.edu",
  "university of oxford": "ox.ac.uk",
  "university of pennsylvania": "upenn.edu",
  "university of pittsburgh": "pitt.edu",
  "university of south carolina": "sc.edu",
  "university of southern california": "usc.edu",
  "university of texas at austin": "utexas.edu",
  "university of toronto": "utoronto.ca",
  "university of washington": "uw.edu",
  "university of wisconsin–madison": "wisc.edu",
  "unreal engine": "unrealengine.com",
  "uob singapore": "uob.com.sg",
  "upstart": "upstart.com",
  "urban outfitters": "urbanoutfitters.com",
  "usa today": "usatoday.com",
  "usaa": "usaa.com",
  "vacasa": "vacasa.com",
  "vacheron constantin": "vacheron-constantin.com",
  "valentino": "valentino.com",
  "valve": "valvesoftware.com",
  "van cleef": "vancleefarpels.com",
  "vanderbilt university": "vanderbilt.edu",
  "vanguard": "vanguard.com",
  "vans": "vans.com",
  "vanta": "vanta.com",
  "varo bank": "varomoney.com",
  "varonis": "varonis.com",
  "veja": "veja-store.com",
  "venmo": "venmo.com",
  "vercel": "vercel.com",
  "verizon": "verizon.com",
  "versace": "versace.com",
  "viator": "viator.com",
  "viber": "viber.com",
  "vice": "vice.com",
  "viking": "vikingcruises.com",
  "vikings": "vikings.com",
  "villanova university": "villanova.edu",
  "vimeo": "vimeo.com",
  "vinfast us": "vinfastauto.com",
  "vinted": "vinted.com",
  "vionic": "vionicshoes.com",
  "virgin atlantic": "virginatlantic.com",
  "virgin australia": "virginaustralia.com",
  "virgin voyages": "virginvoyages.com",
  "virginia tech": "vt.edu",
  "visa": "visa.com",
  "vivobarefoot": "vivobarefoot.com",
  "vodacom": "vodacom.com",
  "vodafone deutschland": "vodafone.com",
  "volkswagen": "volkswagen.com",
  "volkswagen deutschland": "volkswagen.com",
  "volvo": "volvo.com",
  "voot": "voot.com",
  "vox": "vox.com",
  "vpn": "nordvpn.com",
  "vrbo": "vrbo.com",
  "vsco": "vsco.co",
  "vueling airlines": "vueling.com",
  "waffle house": "wafflehouse.com",
  "wake forest university": "wfu.edu",
  "walgreens": "walgreens.com",
  "walmart": "walmart.com",
  "washington commanders": "commanders.com",
  "washington state university": "wsu.edu",
  "washington university in st. louis": "washu.edu",
  "wayfair": "wayfair.com",
  "wealthfront": "wealthfront.com",
  "weaviate": "weaviate.io",
  "webflow": "webflow.com",
  "wechat": "wechat.com",
  "wego": "wego.com",
  "weibo": "weibo.com",
  "weights &amp; biases": "wandb.ai",
  "wells fargo": "wellsfargo.com",
  "wendy&#x27;s": "wendys.com",
  "west virginia university": "wvu.edu",
  "western union": "westernunion.com",
  "westpac": "westpac.com.au",
  "whataburger": "whataburger.com",
  "whatsapp": "whatsapp.com",
  "white castle": "whitecastle.com",
  "white claw hard seltzer": "whiteclaw.com",
  "whole foods market": "wholefoodsmarket.com",
  "william &amp; mary": "wm.edu",
  "wing zone": "wingzone.com",
  "wingstop": "wingstop.com",
  "wired": "wired.com",
  "wise": "wise.com",
  "wish": "wish.com",
  "wiz": "wiz.io",
  "wizz air": "wizzair.com",
  "wolt": "wolt.com",
  "wordpress": "wordpress.com",
  "workday": "workday.com",
  "writer": "writer.com",
  "wyndham hotels": "wyndhamhotels.com",
  "x": "x.com",
  "xai": "x.ai",
  "xbox": "xbox.com",
  "xero": "xero.com",
  "xfinity": "xfinity.com",
  "xiaohongshu": "xiaohongshu.com",
  "xpeng": "xpeng.com",
  "yale": "yale.edu",
  "yale university": "yale.edu",
  "youtube": "youtube.com",
  "youtube music": "music.youtube.com",
  "youtube premium": "youtube.com",
  "yubico": "yubico.com",
  "yum": "yum.com",
  "zalando uk": "zalando.co.uk",
  "zapier": "zapier.com",
  "zappos": "zappos.com",
  "zara": "zara.com",
  "zaxby": "zaxbys.com",
  "zee5": "zee5.com",
  "zelle": "zellepay.com",
  "zendesk": "zendesk.com",
  "zimmer biomet": "zimmerbiomet.com",
  "zocdoc": "zocdoc.com",
  "zomato": "zomato.com",
  "zoom": "zoom.us",
  "zscaler": "zscaler.com",
  "zurich insurance": "zurich.com",
  "zynga": "zynga.com",
  "škoda auto customer journey": "skoda-auto.com",
  "三菱ufjフィナンシャル・グループ": "mufg.jp"
};

// ── BRAND COLORS FOR DYNAMIC UI BORDERS ───────────────────────────────────
export const BRAND_COLORS = {
  'netflix': '#e50914',
  'youtube': '#ff0000',
  'amazon': '#00a8e1',
  'prime': '#00a8e1',
  'hotstar': '#030b14',
  'jio hotstar': '#030b14',
  'sony': '#df1827',
  'sonyliv': '#df1827',
  'zee5': '#8224e3',
  'chatgpt': '#10a37f',
  'claude': '#d97757',
  'canva': '#00c4cc',
  'spotify': '#1db954',
  'discord': '#5865f2',
  'nordvpn': '#4687ff',
  'surfshark': '#00d6aa',
  'disney': '#1f80e0'
};

// ── BRAND CATEGORIES MAPPING ──────────────────────────────────────────────
export const BRAND_CATEGORIES = {
  'netflix': 'Streaming',
  'youtube': 'Streaming',
  'amazon': 'Streaming',
  'prime': 'Streaming',
  'hotstar': 'Streaming',
  'jio hotstar': 'Streaming',
  'sony': 'Streaming',
  'sonyliv': 'Streaming',
  'zee5': 'Streaming',
  'chatgpt': 'AI+',
  'claude': 'AI+',
  'canva': 'AI+',
  'spotify': 'Streaming',
  'nordvpn': 'VPN',
  'surfshark': 'VPN',
  'iptv': 'Streaming',
  'hoichoi': 'Streaming'
};

// ── UTILITY FUNCTIONS ──────────────────────────────────────────────────────

/**
 * Checks if a category name belongs to gaming
 */
export const isGamingCategory = (cat) => {
  if (!cat) return false;
  const c = cat.toLowerCase().trim();
  return c === 'gaming' || c === 'steam' || c === 'playstation' || c === 'xbox' || c === 'epic' || c === 'steam gaming' || c === 'games' || c === 'game' || c.includes('gaming') || c.includes('game');
};

/**
 * Finds matching capsule cover for gaming titles
 */
export const getGameIcon = (gameName) => {
  if (!gameName) return null;
  const cleanName = gameName.toLowerCase().replace(/[^a-z0-9]/g, '');
  for (let key in GAME_IMGS) {
    const cleanKey = key.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (cleanName.includes(cleanKey) || cleanKey.includes(cleanName)) return GAME_IMGS[key];
  }
  return null;
};

/**
 * Extracts a domain name from common logo URL formats
 */
export const getDomainFromUrl = (url) => {
  if (!url) return null;
  if (url.startsWith('data:')) return null;

  try {
    if (url.includes('proxy-image?url=')) {
      const parts = url.split('proxy-image?url=');
      if (parts.length > 1) {
        url = decodeURIComponent(parts[1]);
      }
    }
    
    const urlObj = new URL(url);
    if (urlObj.hostname.includes('google.com') && urlObj.pathname.includes('favicons')) {
      return urlObj.searchParams.get('domain');
    }
    if (urlObj.hostname.includes('logo.dev')) {
      return urlObj.pathname.replace(/^\//, '');
    }
    if (urlObj.hostname.includes('clearbit.com')) {
      return urlObj.pathname.split('/').pop();
    }
    return urlObj.hostname.replace('www.', '');
  } catch (e) {
    // Not a valid URL, try simple substring match if it contains a domain pattern
    const match = url.match(/([a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)/);
    if (match) return match[1];
  }
  return null;
};

// Pre-sorted DOMAIN keys by length descending to ensure longer/more specific brands match first
const SORTED_DOMAIN_KEYS = Object.keys(DOMAINS).sort((a, b) => b.length - a.length);

/**
 * Dynamically resolves Logo.dev, Clearbit, or Google Favicon URLs for a service.
 * Performs dynamic upgrade from google favicon URLs if token is available.
 */
export const getFavicon = (name, customIcon = null) => {
  // 1. If customIcon is provided and is a high-fidelity URL, use it directly!
  if (customIcon) {
    const lowerIcon = customIcon.toLowerCase();
    const isHighFidelity = 
      lowerIcon.startsWith('/') ||
      lowerIcon.includes('logo.dev') ||
      lowerIcon.includes('wikimedia.org') ||
      lowerIcon.includes('steamstatic') ||
      lowerIcon.includes('igdb') ||
      lowerIcon.includes('lutris') ||
      lowerIcon.startsWith('data:image/');

    if (isHighFidelity) {
      if (name) {
        const lowerName = name.toLowerCase().trim();
        if (lowerName.includes('jiohotstar') || lowerName.includes('jio hotstar') || (lowerName.includes('hotstar') && !lowerName.includes('shotstar'))) {
          return '/jiohotstar.png';
        }
      }
      return customIcon;
    }
  }

  // 2. If name matches local brand assets (hoichoi, discovery, lionsgate play, hotstar), return them!
  if (name) {
    const lowerName = name.toLowerCase().trim();
    if (lowerName.includes('hoichoi')) return '/hoichoi.jpg';
    if (lowerName.includes('discovery')) return '/discoveryplus.jpg';
    if (lowerName.includes('lionsgate')) return '/lionsgateplay.jpg';
    if (lowerName.includes('jiohotstar') || lowerName.includes('jio hotstar') || (lowerName.includes('hotstar') && !lowerName.includes('shotstar'))) {
      return '/jiohotstar.png';
    }
  }

  // 3. Fallback check of CUSTOM_ICONS dictionary for other fallback URLs
  if (name) {
    const lowerName = name.toLowerCase().trim();
    const sortedCustomKeys = Object.keys(CUSTOM_ICONS).sort((a, b) => b.length - a.length);
    const matchedCustom = sortedCustomKeys.find(k => lowerName.includes(k));
    if (matchedCustom) return CUSTOM_ICONS[matchedCustom];
  }

  // 4. Also check if customIcon contains signature references to overrides
  if (customIcon) {
    const lowerIcon = customIcon.toLowerCase();
    for (const key of Object.keys(CUSTOM_ICONS)) {
      if (lowerIcon.includes(key)) {
        return CUSTOM_ICONS[key];
      }
    }
  }

  // If customIcon is a local base64 upload or a customized non-favicon, non-cdn URL, return it directly
  if (
    customIcon && 
    !customIcon.includes('google.com/s2/favicons') && 
    !customIcon.includes('clearbit.com') &&
    !customIcon.includes('fallback/lettermark')
  ) {
    return customIcon;
  }

  // 1. Try to extract the domain from the existing customIcon URL
  let domain = null;
  if (customIcon) {
    domain = getDomainFromUrl(customIcon);
  }

  // 2. Fall back to name-based mapping if no domain resolved
  if (!domain && name) {
    const lowerName = name.toLowerCase().trim();
    
    // Check GAME_IMGS
    const gameIcon = getGameIcon(name);
    if (gameIcon) return gameIcon;

    // Resolve domain from DOMAINS dictionary
    const matchedKey = SORTED_DOMAIN_KEYS.find(key => lowerName.includes(key));
    if (matchedKey) {
      domain = DOMAINS[matchedKey];
    } else {
      // Smart domain fallback: sanitize and append .com
      domain = `${lowerName.split(' ')[0].replace(/[^a-z0-9]/g, '')}.com`;
    }
  }

  if (!domain) return null;

  // 3. Use high-fidelity Clearbit CDN cascade
  return `https://logo.clearbit.com/${domain}`;
};

/**
 * Resolves profile/device details from plan descriptions
 */
export const getProfileBadgeDetails = (desc) => {
  if (!desc) return { label: "SHARED PROFILE", color: "#f59e0b" };
  const lower = desc.toLowerCase();
  if (lower.includes("offline")) return { label: "OFFLINE ACTIVATION", color: "#fbbf24" };
  if (lower.includes("private")) return { label: "PRIVATE ACCOUNT", color: "#4ade80" };
  if (lower.includes("personal") || lower.includes("upgrade")) return { label: "PERSONAL UPGRADE", color: "#f472b6" };
  if (lower.includes("shared") || lower.includes("sharing") || lower.includes("seat")) return { label: "SHARED PROFILE", color: "#f59e0b" };
  return { label: "VERIFIED SAFE", color: "#4ade80" };
};
